SW2_AEFS/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

apps/home/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from apps.home import views
from apps.home.views import home,crear_juego, entrar_juego,trivia_juego,resultadostrivia,modificar_balance,puntuaciones,notificaciones,descartar,analitica,ayuda

from apps.home.views import polla
from apps.home.views import jugadores
from apps.home.views import formaciones

from apps.home.views import resultados
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import logout_then_login
from django.contrib.auth.models import User
from apps.home.models import Juego

from . import views
app_name = 'home'

urlpatterns = [
    path('', login_required(home), name='index'),
    #url(r'^trivia$',login_required(views.trivia),name='trivia'),
    path('trivia/<int:juego>',login_required(views.trivia_juego),name='trivia'),
    url(r'^logout$',logout_then_login,name='logout'),
    #url(r'^accounts/', include('apps.accounts.urls')),
    #url(r'^polla$',polla,name='polla'),
    #url(r'^polla/<int:Juego.id>/$',polla,name='polla'),
    #path('polla/<int:Juego.id>/', polla, name='polla'),
    path('polla/<int:juego>', polla, name='polla'),
    path('equipo/<int:juego>',formaciones,name='equipo'),
    #url(r'^equipo$',formaciones,name='equipo'),
    url(r'^crear_juego$',crear_juego,name='crear_juego'),
    #url(r'^entrar_juego/<int:juego>$',entrar_juego,name='entrar_juego'),
    path('estado_cuenta',modificar_balance,name='modificar_balance'),
    path('entrar_juego/<int:juego>/',entrar_juego,name='entrar_juego'),
    path('jugadores/<str:cadena>', jugadores, name='jugadores'),
    #path('polla/<str:username>/', polla, name='polla'),
    path('resultados/<str:cadena>/', resultados, name='resultados'),
    path('resultadostrivia/<str:cadena>/', resultadostrivia, name='resultadostrivia'),
    path('puntuaciones/<int:id_juego>/', puntuaciones, name='puntuaciones'),
    path('descartar/<int:id_juego>/', descartar, name='descartar'),
    path('notificaciones', notificaciones, name='notificaciones'),
    path('analitica', analitica, name='analitica'),
    path('ayuda', ayuda, name='ayuda'),
]

polls/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

proyecto/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.auth.views import login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.accounts.urls',namespace="accounts")),
    #url(r'^login/', include('apps.login.urls', namespace="login")),
    url(r'^home/', include('apps.home.urls', namespace="home")),
]


#url('', login, {'template_name' : 'login/login.html'}, name="login"),

apps/home/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from apps.home.models import Preguntas
from django.contrib.auth.forms import UserCreationForm
from apps.home.models import JuegoForm
from apps.home.models import Juego
from apps.home.models import Jugador
from apps.home.models import Demarcacion
from django.contrib.auth.models import User
from apps.home.models import Partido
from apps.home.models import Formaciones
from apps.home.models import ParticipacionPolla,ParticipacionEquipoIdeal,ParticipacionTrivia,BalanceMonetarioForm,BalanceMonetario,PreguntasTrivia
from django.contrib.auth.decorators import login_required
import datetime
import random
from django.template import RequestContext
from django.contrib import messages
from django.conf import settings
from apps.home.funciones import obtener_score,obtener_cadena,obtener_namespace,obtener_aleatorios,obtener_secuencias
# Create your views here.


def analitica(request):
    return render(request, 'home/analytics.html')

def ayuda(request):
    return render(request, 'home/ayuda.html')

def home(request):
    nombre=request.user.username


    #cadena="{% static 'img/c" +  str(k)  + ".png' %}"

    balance=BalanceMonetario.objects.get(usuario=request.user).balance
    juego=Juego.objects.filter(invitados=request.user)
    k=len(juego)
    cadena=obtener_cadena(k)

    juego2=Juego.objects.filter(privacidad='Publico')
    if balance:
        balance=balance
    else:
        balance=0

    listajuego=list(set(list(juego)+list(juego2)))
    return render(request, 'home/home.html', { 'juego': listajuego, 'user':nombre,'balance':balance, 'cadena':cadena})

def notificaciones(request):
    nombre=request.user.username


    juego=Juego.objects.filter(invitados=request.user)



    return render(request, 'home/notificaciones.html', { 'juego': juego, 'user':nombre})

def crear_juego(request):
    if request.method=='POST':
        form=JuegoForm(request.POST,request.FILES)
        if form.is_valid():
            instance=form.save(commit=False)
            instance.organizador=request.user
            instance.estado='Abierto'
            instance.n=0


            instance.pozo=instance.costo*instance.n_jugadores

            objetobalance=BalanceMonetario.objects.get(usuario=request.user)
            if objetobalance and objetobalance.balance>=instance.costo:
                objetobalance.balance=objetobalance.balance-instance.costo
                objetobalance.save()

                instance=form.save(commit=True)
                instance.save()
            else:
                messages.success(request, "Not Enough Minerals")
                return redirect('home:index')

            if request.user!=instance.invitados:
                instance.invitados.add(request.user)
            instance.save()
            #for User in instance.invitados['invitados']:
            #    instance.invitados.add(User)

            namespace='home:polla'

            #cadena='home:' + str(instance.tipo).lower()
            if str(instance.tipo).lower()=='polla':
                namespace='home:polla'
            elif str(instance.tipo).lower()=='trivia':
                namespace='home:trivia'
            elif str(instance.tipo).lower()=='equipo':
                namespace='home:equipo'
            else:
                namespace='home:polla'

            preguntastriv=[]
            if namespace=='home:trivia':
                temp=Preguntas.objects.all().order_by('id')
                preguntas=obtener_aleatorios(temp)
                preguntastriv = PreguntasTrivia(juego=instance)
                for p in preguntas:
                    preguntastriv.preguntas_juego.add(p)

                preguntastriv.save()


            return redirect(namespace, instance.id)
            #return redirect(cadena(instance),instance)
    else:
        form=JuegoForm()
    return render(request, 'home/crear_juego.html', {'form':form})


def entrar_juego(request,juego):
    id_jug=juego
    #tipo_jug=tipo
    tipo_jug=Juego.objects.get(id=id_jug).tipo.lower()
    juego=Juego.objects.get(id=id_jug)



    namespace=obtener_namespace(tipo_jug)
    condicion=False
    objetos=[]
    if tipo_jug == 'polla':
        objetos = ParticipacionPolla.objects.all()

    elif tipo_jug == 'equipo':
        objetos = ParticipacionEquipoIdeal.objects.all()
    else:
        objetos = ParticipacionTrivia.objects.all()

    for o in objetos:
        if o.usuario==request.user and o.juego==juego:
            condicion=True
            break

    if condicion:
        messages.success(request, "Ya jugaste este juego")
        return redirect('home:index')
    else:
        objetobalance=BalanceMonetario.objects.get(usuario=request.user)
        if objetobalance and objetobalance.balance>=juego.costo:
            objetobalance.balance=objetobalance.balance-juego.costo
            objetobalance.save()
            return redirect(namespace, id_jug)
        else:
            messages.success(request, "Not Enough Minerals")
            return redirect('home:index')

def jugadores(request, cadena):
    division=cadena.split('&')

    formacion_id=int(division[0])
    jug_id=int(division[1])
    juego=Juego.objects.get(id=jug_id)
    if request.method == 'POST':
        rawform = request.body
        params = str(rawform).split('&')

        jugadores = []
        for i in range(0, len(params)):
            if 'jugador' in params[i]:
                old = params[i].split('=')[1]
                n1 = old.replace("'","")
                n2 = n1.replace('"','')
                jugadores.append(int(n2))

        ataque = 0
        defensa = 0
        velocidad = 0
        for j in jugadores:
            jugador = Jugador.objects.get(id=j)
            ataque = ataque + jugador.ataque
            defensa = defensa + jugador.defensa
            velocidad = velocidad + jugador.velocidad



        ataque_medio = round(ataque/11, 3)

        defensa_media = round(defensa/11, 3)

        velocidad_media = round(velocidad/11, 3)


        score = obtener_score(ataque_medio,defensa_media,velocidad_media)




        contexto = {'ataque_medio' : ataque_medio,
        'defensa_media' : defensa_media,
        'velocidad_media' : velocidad_media,
        'score' : score,
        'juego':juego }
        user = request.user
        fecha = datetime.datetime.now()
        formatedDate = fecha.strftime("%Y-%m-%d %H:%M:%S")
        participacion = ParticipacionEquipoIdeal(usuario=user, ataque=ataque_medio, defensa=defensa_media,
        velocidad=velocidad_media,score=score, fecha=formatedDate, juego=juego)
        participacion.save()

        juego.n += 1
        if juego.n >= juego.n_jugadores:
            participaciones=ParticipacionEquipoIdeal.objects.filter(juego=juego)
            max=0
            ganadores=[]
            for i in participaciones:
                if i.score>max:
                    max=i.score
            for i in participaciones:
                if i.score==max:
                    ganadores.append(i.usuario)
            for j in ganadores:
                balancemonetario=BalanceMonetario.objects.get(usuario=j)
                balancemonetario.balance=balancemonetario.balance+juego.pozo/len(ganadores)
                balancemonetario.save()
            juego.estado='Cerrado'
        juego.save()

        return render(request, 'equipoideal/resultados.html', contexto)
    else:
        formacion = Formaciones.objects.get(id=formacion_id)
        jugadores = Jugador.objects.all().order_by('id')
        arqueros = []
        defensas = []
        centrocampistas = []
        delanteros = []
        arquero = Demarcacion.objects.get(nombre='ARQUERO')
        defensa = Demarcacion.objects.get(nombre='DEFENSA')
        centrocampista = Demarcacion.objects.get(nombre='CENTROCAMPISTA')
        for jugador in jugadores:
            if jugador.demarcacion == arquero:
                arqueros.append(jugador)
            elif jugador.demarcacion == defensa:
                defensas.append(jugador)
            elif jugador.demarcacion == centrocampista:
                centrocampistas.append(jugador)
            else:
                delanteros.append(jugador)

        lst_defs = []
        print('cantidad de defensas: {}'.format(formacion.cantidad_defensas))
        cant_defs = formacion.cantidad_defensas
        for i in range(0, cant_defs):
            lst_defs.append(defensas)

        lst_cent = []
        print('cantidad de centros: {}'.format(formacion.cantidad_centrocampistas))
        for j in range(0, formacion.cantidad_centrocampistas):
            lst_cent.append(centrocampistas)

        lst_dela = []
        for k in range(0, formacion.cantidad_delanteros):
            lst_dela.append(delanteros)

        contexto = {'formacion' : formacion, 'arqueros' : arqueros,
        'lst_defs' : lst_defs, 'lst_cent' : lst_cent,
        'lst_dela' : lst_dela}

        return render(request, 'equipoideal/jugadores.html', contexto)



def polla(request, juego):
    #juego=request.POST.get('juego')
    juego=Juego.objects.get(id=juego)
    partidos = Partido.objects.all().order_by('id')
    contexto = {'partidos' : partidos}
    if request.method == 'POST':
        score = 0
        form = request.POST
        longitud = len(form)-1
        for x in partidos:
            i=form['a_partido_id={}'.format(x.id)]
            if i == str(x.resultado):
                score = score + 1
        user = request.user
        fecha = datetime.datetime.now()
        formatedDate = fecha.strftime("%Y-%m-%d %H:%M:%S")
        participacion = ParticipacionPolla(usuario=user, score=score, fecha=formatedDate, juego=juego)
        participacion.save()
        juego.n += 1
        if juego.n >= juego.n_jugadores:
            participaciones=ParticipacionPolla.objects.filter(juego=juego)
            max=0
            ganadores=[]
            for i in participaciones:

templates/home/analytics.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block header %}
<h4>Universidad de Lima</h4>
{% endblock %}
{% block content %}

              <script src="{% static 'js/plotly-latest.min.js' %}"></script>
              <script src="{% static 'js/angular.min.js' %}"></script>
              <script src="{% static 'js/analiticas.js' %}"></script>
              <div class="container">
                          <form action="{% url 'home:index' %}" method="post">
                              {% csrf_token %}
                              <button class="btn-large waves-effect waves-red blue darken-1 amber lighten-5-text" type="submit">Volver</button>
                          </form>
                            </div>
                            <br>
                            <br>

<div ng-app="analiticas" ng-controller="reporte1">

  <div id="visitas">
  </div>
  <div class="row">
    <div id="browsers">
    </div>
    <div id="plataformas">
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th>
          <div class="row" align="center">
            Tipo
            <input type="text" ng-model="search.Tipo">
          </div>
        </th>
        <th>
          <div class="row" align="center">
            Browser
            <input type="text" ng-model="search.Browser">
          </div>
        </th>
        <th>
          <div class="row" align="center">
            URL_Actual
            <input type="text" ng-model="search.URL_Actual">
          </div>
        </th>
        <th>
          <div class="row" align="center">
            Url Destino
            <input type="text" ng-model="search.URL_Destino">
          </div>
        </th>
        <th>
          <div class="row" align="center">
            Plataforma
            <input type="text" ng-model="search.Plataforma">
          </div>
        </th>
        <th>
          <div class="row" align="center">
            Lenguaje
            <input type="text" ng-model="search.Language">
          </div>
        </th>
        <th>
          <div class="row" align="center">
            Fecha
            <input type="text" ng-model="search.Fecha">
          </div>
        </th>
      </tr>
    </thead>
    <tbody>
      {% verbatim %}
      <tr ng-repeat="ev in eventos | orderBy:'-Fecha'| filter:search:strict">
        <td>{{ ev.Tipo }}</td>
        <td>{{ ev.Browser }}</td>
        <td>{{ ev.URL_Actual }}</td>
        <td>{{ ev.URL_Destino }}</td>
        <td>{{ ev.Plataforma }}</td>
        <td>{{ ev.Language }}</td>
        <td>{{ ev.Fecha }}</td>
      {% endverbatim %}
      </tr>
    </tbody>
  </table>
</div>

            {% endblock %}
            {% block footer %}


            <h5>Lima, Peru 2018</h5>
            {% endblock %}

templates/home/ayuda.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block header %}
<h4>Universidad de Lima</h4>
{% endblock %}
{% block content %}
  <br>
<div id="divCabecera">

  <div class="container">
              <form class="logout-link" action="{% url 'home:index' %}" method="post">
                  {% csrf_token %}
                  <button class="btn btn-success" type="submit">Volver</button>
              </form>
                </div>

                <br>
                  <br>
                  <div class="card-panel indigo darken-4 text-white">
<h2 style="color:#ffffff;"> Ayuda </h2>
<br>
<h3 style="color:#ffffff;"> Cómo Jugar </h3>

<p style="color:#ffffff;" class="flow-text">  ¡Para jugar basta unirse a una sala y empezar a demostrar tus habilidades! Puedes jugar con amigos o con cualquier usuario de la aplicación.
Para entrar a una sala solo basta hacer click en "Entrar" en el lobby de la pantalla principal. Presionando sobre la campana de notificaciones puedes ver los juegos a los que haz sido invitado.
También puedes elegir crear un nuevo juego, donde podrás elegir el monto de entrada, el tipo de juego y los jugadores invitados. Hay 3 modalidades de juego, Polla, Trivia y Equipo Ideal.
Todos los juegos pueden jugarse gratis o en modo apuesta. ¡A jugar!</p>

<br>
<h4 style="color:#ffffff;" > Polla </h4>

<p style="color:#ffffff;" class="flow-text"> El juego polla es una apuesta. ¡Mira quien de tus amigos conoce más el deporte! Se apostarán sobre el resultado de los partidos que se jugarán.
El jugador que tenga más aciertos ganará.</p>

<h4 style="color:#ffffff;"> Equipo Ideal </h4>
<p style="color:#ffffff;" class="flow-text"> ¿Tienes a tu formación ideal en mente? ¡Ponla a prueba con Equipo Ideal! ¡Elige los jugadores que compondrán tu equipo ganador y comparalo con el de tus amigos para ver quien tuvo la mejor composición!</p>

<h4 style="color:#ffffff;"> Trivia </h4>
<p style="color:#ffffff;" class="flow-text"> ¿Quién es el más sabelotodo? ¡Pon a prueba tus conocimientos con Trivia! Desde las preguntas más inusuales hasta las más difíciles.
Compite por ver quién es el más fanático del fútbol.</p>






</div>
</div>
<br>
<br>
  <img style="height:400px;width:600px;" src=" {% static 'img/ayuda.jpg' %}"  alt="ayuda" />
<br>
<br>
{% endblock %}
{% block footer %}


<h5>Lima, Peru 2018</h5>
{% endblock %}

templates/home/crear_juego.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block header %}
<h4>Universidad de Lima</h4>
{% endblock %}
{% block content %}
{% load staticfiles %}




  <br>
    <br>
              

<br>
<br>
                              <div class="container">
                                          <form class="logout-link" action="{% url 'home:index' %}" method="post">
                                              {% csrf_token %}
                                              <button class="btn btn-success" type="submit">Volver</button>
                                          </form>
                                            </div>





  <body>
    <div class="container">
<form method="post" action="{% url 'home:crear_juego' %}">
  {% csrf_token %}
  <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
      <div class="row">
        {{ form.as_p }}




      </div>
      <div align="center">
        <button class="btn btn-primary" type="submit">Crear</button>
      </div>
    </div>
    <div class="col-md-3">
    </div>
  </div>
</form>

<img style="height:400px;width:600px;" src=" {% static 'img/crear.jpg' %}"  alt="crear" />
</div>

{% endblock %}
{% block footer %}


<h5>Lima, Peru 2018</h5>
{% endblock %}

templates/home/crearjuego.html
{% extends 'base/base.html' %}

{% block title %} Crear Juego {% endblock %}
{% block header %}
{% endblock %}
{% block content %}
<form method="post">
  {% csrf_token %}
  <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
      <div class="row">
        {{ form.as_p }}
      </div>
      <div align="center">
        <button class="btn" type="submit">Crear</button>
      </div>
    </div>
    <div class="col-md-3">
    </div>
  </div>
</form>
{% endblock %}
{% block footer %}
{% endblock %}

templates/home/home.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block header %}
<h4>Universidad de Lima</h4>
{% endblock %}
{% block content %}
<script> $(document).ready(function(){
   $('.tooltipped').tooltip({delay: 50});
 }); </script>

<div id="divCabecera">
<div>
<table class="table bordered"> <tbody> <tr><td> Bienvenido, </td></tr>

  <tr><td style="font-size: 20px;" class="text-indigo darken-4 z-depth-4"> {{user}} </td></tr>
  </tbody>





 </table>
   </div>
   <br>
   <br>

   <div>


     </div>
  </div>
  <div >
  <div class="z-depth-4" style="width:35%;float:left;">
  <div>
    <table class="table bordered"> <tbody> <tr><td> Saldo Disponible </td></tr>

      <tr><td style="font-size: 2.0vw;" class="text-green accent-3"> S/.{{ balance }}</td></tr>
      </tbody>





     </table>
       </div>

     <div >
  <button name="balance" class="waves-effect waves-light red btn-large" type="submit"><a class="white-text" href={% url 'home:modificar_balance' %}>Estado de Cuenta</a></button>


     </div>


</div>
<div style="float:right;padding-right: 2vw;">
  <a href={% url 'home:notificaciones' %}>  <img style="height:150px;width:150px;" src=" {{ cadena }} " alt="notifcaciones" /> </a>
</div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>


<table class='highlight bordered'>
<thead> <tr><th>Juego Creados</th><th>Tipo de Juego</th><th>Creador</th><th>Costo</th><th>Invitados</th><th>Unirse</th><th>Puntuaciones</th></tr> </thead>
<tbody>
{% for j in juego %}
  <tr><td>  {{ j.nombre }} ( {{j.n}}/{{ j.n_jugadores }})   </td><td>{{ j.tipo }} </td> <td> {{ j.organizador }} </td><td> S/.{{ j.costo }} </td> <td>
{% for i in j.invitados.all %}


<div class="chip">
    <img src="{% static 'img/football.png' %}" alt="Contact Person">
    {{ i.username }}
  </div>

{% endfor %}
{% if j.n < j.n_jugadores %}
<td>
  <button name="juego" class="waves-effect waves-light purple darken-3"
  type="submit">
    <a class="white-text"
      href={% url 'home:entrar_juego' juego=j.id %}>
      Entrar
    </a>
  </button>
</td>
{% else %}
<td>
  Cerrado
</td>
{% endif %}
<td> <button type="button"
  class="waves-effect waves-light blue darken-3">
    <a class="white-text"
      href={% url 'home:puntuaciones' id_juego=j.id %}>
      Posiciones
    </a>
  </button>
</td>
</tr>
{% endfor %}

  </tbody>
</table>
<br>
     <div>
         <div style="float:left;">
           <a class="white-text" href={% url 'home:crear_juego' %} onclick="enviar_evento()" id="GuardarEvento" name="Crear" ><button name="juego" class="waves-effect waves-light red btn-large" type="submit"> Crear Juego </button></a>
         </div>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
         <div class="center-align">
            <a class="tooltipped" data-position="bottom" data-delay="30" data-tooltip="Ayuda" href={% url 'home:ayuda' %}> <img style="height:63px;width:63px;" src=" {% static 'img/interrogacion.png' %}" onmouseover="this.src='/static/img/interrogacion2.png';" onmouseout="this.src='/static/img/interrogacion.png';" alt="ayuda" /> </a>
         </div>
{% if request.user.is_superuser %}
         <div style="float:right;padding-right: 2vw;">
           <a href={% url 'home:analitica' %}>  <img style="height:150px;width:150px;" src=" {% static 'img/analytics.png' %}" alt="analitica" /> </a>
           <p class="flow-text"> Analítica </p>
         </div>

         {% endif %}
</div>
<br>
<br>
<br>
<br>
{% endblock %}
{% block footer %}


<h5>Lima, Peru 2018</h5>
{% endblock %}

templates/home/notificaciones.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block header %}
<h4>Universidad de Lima</h4>
{% endblock %}
{% block content %}

<div id="divCabecera">
<div>
<table class="table bordered"> <tbody> <tr><td> Juegos a los que fuiste invitado:</td></tr>

  <tr><td style="font-size: 20px;" class="text-indigo darken-4 z-depth-4"> {{user}} </td></tr>
  </tbody>





 </table>
   </div>
   <br>
   <br>

   <div>


     </div>
  </div>

  <div class="container">
              <form class="logout-link" action="{% url 'home:index' %}" method="post">
                  {% csrf_token %}
                  <button class="btn btn-success" type="submit">Volver</button>
              </form>
                </div>


<br>
<br>


<table class='highlight bordered'>
<thead> <tr><th>Juego Creados</th><th>Tipo de Juego</th><th>Creador</th><th>Costo</th><th>Invitados</th><th>Unirse</th><th>Descartar</th></tr> </thead>
<tbody>
{% for j in juego %}
  <tr><td>  {{ j.nombre }} ( {{j.n}}/{{ j.n_jugadores }})   </td><td>{{ j.tipo }} </td> <td> {{ j.organizador }} </td><td> S/.{{ j.costo }} </td> <td>
{% for i in j.invitados.all %}


<div class="chip">
    <img src="{% static 'img/football.png' %}" alt="Contact Person">
    {{ i.username }}
  </div>

{% endfor %}
{% if j.n < j.n_jugadores %}
<td>
  <button name="juego" class="waves-effect waves-light purple darken-3"
  type="submit">
    <a class="white-text"
      href={% url 'home:entrar_juego' juego=j.id %}>
      Entrar
    </a>
  </button>
</td>
{% else %}
<td>
  Cerrado
</td>
{% endif %}
<td>
  <a href={% url 'home:descartar' id_juego=j.id %}>  <img style="height:52px;width:52px;" src="{% static 'img/equis.png'%}" alt="descartar" /> </a>
</td>
</tr>
{% endfor %}

  </tbody>
</table>
<br>

         <div>
           <a class="white-text" href={% url 'home:crear_juego' %}><button name="juego" class="waves-effect waves-light red btn-large" type="submit"> Crear Juego </button></a>
         </div>

<br>
{% endblock %}
{% block footer %}
<h5>Lima, Peru 2018</h5>
{% endblock %}

templates/home/resultadostrivia.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block title %} RESULTADOS {% endblock %}
{% block content %}
<div class="container">
  <div class="container">
              <form action="{% url 'home:index' %}" method="post">
                  {% csrf_token %}
                  <button class="btn-large waves-effect waves-red blue darken-1 amber lighten-5-text" type="submit">Volver</button>
              </form>
                </div>
<br>
<br>
<div class="container">
                <td> <button type="button"
                  class="waves-effect waves-light blue darken-3"  >
                    <a class="white-text " onclick="enviar_evento()" id="GuardarEvento" name="puntuaciones"
                      href={% url 'home:puntuaciones' id_juego=juego.id %}>
                      Posiciones
                    </a>
                  </button>
                </td>

                </div>
</div>
<div class="container">
  <div align="center">
    <h1>Su puntaje es: {{score}} de {{ preguntas|length }}</h1>
  </div>
  <br>
  <h3>Resultados de trivia: </h3>
  <table class="table">
    <thead>
      {% if preguntas %}
      {% for pregunta in preguntas %}
      <th>{{ pregunta.id }}</th>

      {% endfor %}
      {% endif %}
    </thead>
    <tbody>


      <tr>
        {% for pregunta in preguntas %}
        <td>{{ pregunta.pregunta }}</td>

        {% endfor %}

      </tr>


    </tbody>
  </table>
</div>
{% endblock %}