SW2_AEFS/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

proyecto/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.auth.views import login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.accounts.urls',namespace="accounts")),
    #url(r'^login/', include('apps.login.urls', namespace="login")),
    url(r'^home/', include('apps.home.urls', namespace="home")),
]


#url('', login, {'template_name' : 'login/login.html'}, name="login"),

templates/polla/polla.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block title %} POLLA {% endblock %}
{% block content %}
<div class="container">
  <form method="post">
    {% csrf_token %}
    <table class="table">
      <thead>
        <th>Equipo Local</th>
        <th>Equipo Visita</th>
        <th>Fecha Partido</th>
        <th>Quien gana?</th>
      </thead>
      <tbody>
        {% if partidos %}
        {% for partido in partidos %}
        <tr>
          <td>{{ partido.eq_local }}</td>
          <td>{{ partido.eq_visita }}</td>
          <td>{{ partido.fecha }}</td>
          <td>
            <input class="with-gap"  type="radio" name="a_partido_id={{ partido.id }}" value="1" id="{{ partido.id }}&rd1">  <label for="{{ partido.id }}&rd1">Gana local</label><br>
            <input class="with-gap"  type="radio" name="a_partido_id={{ partido.id }}" value="2" id="{{ partido.id }}&rd2"> <label for="{{ partido.id }}&rd2">Gana visita</label><br>
            <input class="with-gap"  type="radio" name="a_partido_id={{ partido.id }}" value="3" id="{{ partido.id }}&rd3"> <label for="{{ partido.id }}&rd3">Empate</label>
          </td>
        </tr>
        {% endfor %}
        {% endif %}
      </tbody>
    </table>
    <div align="center">
        <button class="btn" type="submit">Enviar Polla</button>
    </div>
  </form>
</div>
{% endblock %}

templates/polla/resultados.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block title %} RESULTADOS {% endblock %}
{% block content %}
<div class="container">
  <div class="container">
              <form action="{% url 'home:index' %}" method="post">
                  {% csrf_token %}
                  <button class="btn-large waves-effect waves-red blue darken-1 amber lighten-5-text" type="submit">Volver</button>
              </form>
                </div>
                <br>
                <br>
                <div class="container">
                                <td> <button type="button"
                                  class="waves-effect waves-light blue darken-3" >
                                    <a class="white-text" onclick="enviar_evento()" id="GuardarEvento" name="puntuaciones"
                                      href={% url 'home:puntuaciones' id_juego=juego.id %}>
                                      Posiciones
                                    </a>
                                  </button>
                                </td>

                                </div>

</div>
<div class="container">
  <div align="center">
    <h1>Su puntaje es: {{score}} de {{ partidos|length }}</h1>
  </div>
  <br>
  <h3>Resultados de los partidos: </h3>
  <table class="table">
    <thead>
      <th>Equipo Local</th>
      <th>Equipo Visita</th>
      <th>Fecha</th>
      <th>Victoria</th>
    </thead>
    <tbody>
      {% if partidos %}
      {% for partido in partidos %}
      <tr>
        <td>{{ partido.eq_local }}</td>
        <td>{{ partido.eq_visita }}</td>
        <td>{{ partido.fecha }}</td>

        {% if partido.resultado == 1 %}
          <td>Local</td>
        {% elif partido.resultado == 2 %}
          <td>Visita</td>
        {% else %}
          <td>Empate  </td>
        {% endif %}
      </tr>
      {% endfor %}
      {% endif %}
    </tbody>
  </table>
</div>
{% endblock %}